#!/bin/bash -eu

sudo apt-get install libevent-dev
pip install $DJANGO --use-mirrors
make bootstrap
if [[ ${TRAVIS_PYTHON_VERSION::1} == '2' ]]; then
	pip install gevent --use-mirrors
fi
if [[ ${TRAVIS_PYTHON_VERSION} == '3.2' ]]; then
	pip install -I https://github.com/celery/celery/archive/3.0.zip
fi
if [[ ${TRAVIS_PYTHON_VERSION::1} == '3' ]]; then
	pip uninstall django-celery -y
fi
