#!/bin/bash -eu

pip install $DJANGO
make bootstrap
if [[ ${TRAVIS_PYTHON_VERSION::1} == '2' ]]; then
	pip install gevent
fi
if [[ ${TRAVIS_PYTHON_VERSION} == '3.2' ]]; then
	pip install -I https://github.com/celery/celery/archive/3.0.zip
fi
if [[ ${TRAVIS_PYTHON_VERSION::1} == '3' ]]; then
	pip uninstall django-celery -y
fi
